name: 📚 Documentation
description: Report an issue related to documentation
title: "[DOCS]: "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our documentation!

  - type: dropdown
    id: documentation-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect documentation
        - Confusing documentation
        - Outdated documentation
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation that needs to be improved?
      placeholder: URL, file path, or page name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what's wrong with the current documentation.
      placeholder: The documentation is missing information about...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What information should be added or modified?
      placeholder: I recommend adding/changing...
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to help improve this documentation?
      options:
        - Yes, I can submit a PR with the changes
        - No, I'm not able to contribute to the documentation
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false